<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Test Suite for all Test Cases Depending on File Upload Center</description>
   <name>File Upload Center</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-01-29T12:06:12</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ff60b731-f14f-45e3-9e66-0b56f1d996c1</testSuiteGuid>
   <testCaseLink>
      <guid>0411ceb0-12ee-4bb2-9a05-2509c7e6fe8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/File Upload Center Module/verify_User is able to Upload Payment File</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c7f9223-3507-4a3e-8e08-24b04c1ba285</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d38a1a3d-b62b-4283-8554-f300d6bcb062</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38aecce2-b922-4390-b666-7d3f8e6aa13f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>362f9c38-ccf7-4710-b500-b113413d29b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0f0adf9-5d0d-4b7b-a08c-9e1b9eafc72f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1556b507-0596-45b1-9f3e-7cc7748facdc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>545e09b9-5063-498f-892a-c5e60aabb5ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payments/Makeover Overpayment/verify_Make overpayment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02ce6715-1eba-436f-8acc-ed857de293f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad980be0-6e55-4727-9092-fc707f12b2c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58750736-3b51-4123-b4de-15bd0195d511</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e1405a6-ce57-484b-a18c-708abb93b998</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fce1f8a-ddac-4891-9445-70f441fa4301</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73b053c5-26af-409d-aef7-072d11852d96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payments/Confirm Payments/verify_Customer Payment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6024dd6-cf55-4095-a04a-66505c2b2692</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>821d9392-8119-42b4-b1fb-0f21005337c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>056f2335-96ca-41d3-9ffe-e2c4678edb82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bafc285f-cc27-47a7-8815-2c4980340d06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0449f692-281c-4b94-8780-bf072498f4fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payments/Confirm Payments/verify_Dealer Payment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a200375-796e-4370-855f-c48151a0161d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acb3661a-0dda-4dbb-b944-356623a7ae85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b437d42c-ae76-435f-a4cb-b94b1ca45656</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0af5721-8572-4abd-ab37-0fd3f13c7cb2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4093a9f6-0ec5-4bac-b404-88608d2d5a72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payments/Edit Cash payment plan name and display name/verify_name and Display name are Editable</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6cc9021-0df8-464e-9642-a1f37b5a9b0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8d5160e-e86a-40c4-b49a-795e0eaf9905</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14a6a52d-7d6e-4ea3-8cd2-4d78c181be47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4a901f5-e49f-40d3-8bdc-3aa74db3fd63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a319a787-ff9c-4b89-9fa1-17aa038ffd9b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
