<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SaveRefundApproval</name>
   <tag></tag>
   <elementGuidId>92e160b7-a2c4-419a-9598-c556213d6874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/div/div[3]/fieldset/div/form/table/tbody/tr[3]/td/input</value>
   </webElementProperties>
</WebElementEntity>
