<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Close_WindowforRefund</name>
   <tag></tag>
   <elementGuidId>615dd763-f840-4a29-9aa5-8a3869a54f82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='wdw-payment-details']//span[text()='Close']</value>
   </webElementProperties>
</WebElementEntity>
