<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>credits</name>
   <tag></tag>
   <elementGuidId>4d75619c-193a-4c59-9841-be5c7ef40a27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='div-account-info']/div[1]/div/div[5]/div[1]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
