<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>message_RefundSuccessfull</name>
   <tag></tag>
   <elementGuidId>18064d90-de67-440e-95fe-e9e3d542f5c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='addRefundDiv']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='addRefundDiv']/div/div</value>
   </webElementProperties>
</WebElementEntity>
