<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DropDown-ProductAccount</name>
   <tag></tag>
   <elementGuidId>916dd75e-3a6b-4c6a-b747-5b4ce122fc5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='customer-div']/form/div[5]/div/div/span[2]/span</value>
   </webElementProperties>
</WebElementEntity>
