<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input-ProductAccount</name>
   <tag></tag>
   <elementGuidId>2f9cde93-9388-4dd5-ae78-16c2eaa79b53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='customer-div']/form/div[5]/div/div/span[1]</value>
   </webElementProperties>
</WebElementEntity>
