<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_CashPaymentListName</name>
   <tag></tag>
   <elementGuidId>f5a38d31-cf06-431f-b107-a23c8e3d03d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='ListCashPaymentPlans']/table/tbody/tr[td[text()='PaymentPlan1']]</value>
   </webElementProperties>
</WebElementEntity>
