<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drop_CustomerPaymentHistoryLog_paymentDetails</name>
   <tag></tag>
   <elementGuidId>4b9c662e-5785-4712-bba4-8ffcad052be7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='history_logs_panel']/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='history_logs_panel']/li[1]/a</value>
   </webElementProperties>
</WebElementEntity>
