<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lastAmountpaid</name>
   <tag></tag>
   <elementGuidId>6aa7bfbf-8983-46b2-bad9-f10f0abd7c55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='div-last-payment-info']/div[1]/div[1]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
