<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_ApproveStatus1</name>
   <tag></tag>
   <elementGuidId>83771f64-1aad-48a2-a045-1f22d4fd7fb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[5]/div/ul/li[text()='Approved']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[5]/div/ul/li[text()='Approved']</value>
   </webElementProperties>
</WebElementEntity>
