<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drop_productAccount</name>
   <tag></tag>
   <elementGuidId>5853c57f-0070-4f81-b019-82eadf572b40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='customer-div']/form/div[4]/div/div/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='customer-div']/form/div[4]/div/div/span[2]/span</value>
   </webElementProperties>
</WebElementEntity>
