<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link-ListCashPaymentPlans</name>
   <tag></tag>
   <elementGuidId>55152082-ba18-48c3-9d75-06f5186c48e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@href=&quot;/Accounts/CashPaymentPlan/List&quot;]</value>
   </webElementProperties>
</WebElementEntity>
