<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link-ApproveCustomerRefund</name>
   <tag></tag>
   <elementGuidId>1127db02-689d-41e1-b7b1-06795c2b43b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@href=&quot;/Accounts/ProductRefund/ListForApproval&quot;]</value>
   </webElementProperties>
</WebElementEntity>
