<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link-FloatingPayments</name>
   <tag></tag>
   <elementGuidId>556c0784-da47-4998-ad95-d46bbd6fb379</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@href=&quot;/Payment/PayerPayments/Floating&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@href=&quot;/Payment/PayerPayments/Floating&quot;]</value>
   </webElementProperties>
</WebElementEntity>
