<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_CreditSystem</name>
   <tag></tag>
   <elementGuidId>0fbd4a97-1d6c-42f8-afc6-b14d75e7e582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/form/table/tbody/tr[8]/td[4]/div/div/span[2]/span</value>
   </webElementProperties>
</WebElementEntity>
