<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_LoanType</name>
   <tag></tag>
   <elementGuidId>5cd623bc-b149-46b3-a6b6-dcd4acc11502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/form/table/tbody/tr[10]/td[2]/div/div/span[2]/span</value>
   </webElementProperties>
</WebElementEntity>
